const LANG = {
    "en": {
        "start": "Start",
        "continue": "Continue",
        "level-select": "Select Level",
        "how-to-play": "How to Play",
        "short-tap": "Short Tap:",
        "long-tap": "Long Tap:",
        "next-level": "Next Level",
        "restart-message": "Restart Level?",
        "no": "No",
        "yes": "Yes",
        "page": "Page",
        "no-more-houses": "No more houses left.",
        "no-more-house-to-path": "Cannot turn house into path as there are no more left.",
        "no-more-paths": "No more paths left.",
        "no-more-path-to-house": "Cannot turn path into house as there are no more left.",
        "no-more-bridges": "No more bridges left.",
        "house-isolated": "Houses must be placed next to a path or bridge.",
        "path-isolated": "Not next to another path or bridge to stay connected.",
        "bridge-isolated": "Bridges must be placed next to a path to stay connected.",
        "house-isolated-by-house": "Turning this path into a house would isolate neighboring houses.",
        "house-isolated-by-path": "Removing this path would isolate neighboring houses.",
        "house-isolated-by-bridge": "Removing this bridge would isolate neighboring houses.",
        "path-to-house-isolated": "Cannot turn path into house as it would be isolated.",
        "adjacent-bridges": "Bridges cannot be placed next to each other.",
        "disconnected-by-house": "Turning this path into a house would disconnect paths and bridges.",
        "disconnected-by-path": "Removing this path would disconnect other paths and bridges.",
        "disconnected-by-bridge": "Removing this bridge would disconnect other paths and bridges.",
        "hint-no-tiles": "Place some houses, paths or bridges first.",
        "hint-action": "The HINT-button will then reveal which tiles are right or wrong.",
        "hint-no-new-tiles": "All existing house, path and bridge tiles already have a hint.",
        "hint-place-new-tiles": "Place new tiles before pressing the HINT-button again.",
        "htp-title": "How to Play",
        "htp-intro": "*Settlement* is a puzzle game about building a village into a given landscape of *grass*, *water* and *tree* tiles.",
        "htp-village": "You place *houses* and *paths* on grass tiles, and *bridges* on water tiles. Tree tiles are just obstacles.",
        "htp-goal": "Your *goal* is to place exactly as many houses, paths and bridges as stated at the top of the screen.",
        "htp-rules": "But there are some *rules* you must follow:",
        "htp-rule-connected": "All *path* and *bridge* tiles must be *connected*. Villagers must be able to walk from any path or bridge to any other.",
        "htp-rule-isolation": "Each *house* must be *next to* a path or bridge tile. Villagers cannot get to their houses if they are isolated.",
        "htp-rule-bridge": "*Bridge* tiles must not be placed *next to* each other. Villagers are not able to build large bridges that span more than one tile."
    },
    "de": {
        "start": "Starten",
        "continue": "Fortsetzen",
        "level-select": "Level auswählen",
        "how-to-play": "Anleitung",
        "short-tap": "Kurz antippen:",
        "long-tap": "Lang antippen:",
        "next-level": "Nächstes Level",
        "restart-message": "Level neustarten?",
        "no": "Nein",
        "yes": "Ja",
        "page": "Seite",
        "no-more-houses": "Keine Häuser mehr übrig.",
        "no-more-house-to-path": "Keine Wege mehr übrig, um Haus in Weg umzuwandeln.",
        "no-more-paths": "Keine Wege mehr übrig.",
        "no-more-path-to-house": "Keine Häuser mehr übrig, um Weg in Haus umzuwandeln.",
        "no-more-bridges": "Keine Brücken mehr übrig.",
        "house-isolated": "Häuser müssen neben Wegen oder Brücken platziert werden.",
        "path-isolated": "Wege müssen mit anderen Wegen und Brücken verbunden bleiben.",
        "bridge-isolated": "Brücken müssen mit Wegen verbunden bleiben.",
        "house-isolated-by-house": "Weg in Haus umzuwandeln, würde benachbarte Häuser abschneiden.",
        "house-isolated-by-path": "Diesen Weg zu entfernen, würde benachbarte Häuser abschneiden.",
        "house-isolated-by-bridge": "Diese Brücke zu entfernen, würde benachbarte Häuser abschneiden.",
        "path-to-house-isolated": "Umwandlung von Weg würde ein abgeschnittenes Haus erzeugen.",
        "adjacent-bridges": "Brücken können nicht nebeneinander gesetzt werden.",
        "disconnected-by-house": "Umwandlung von Weg in Haus würde Wege und Brücken trennen.",
        "disconnected-by-path": "Diesen Weg zu entfernen, würde andere Wege und Brücken trennen.",
        "disconnected-by-bridge": "Diese Brücke zu entfernen, würde Wege und Brücken trennen.",
        "hint-no-tiles": "Platziere zunächst Häuser, Wege oder Brücken.",
        "hint-action": "Danach kannst du dir Hinweise für diese anzeigen lassen.",
        "hint-no-new-tiles": "Bestehende Häuser, Wege und Brücken haben bereits einen Hinweis.",
        "hint-place-new-tiles": "Platziere weitere, um neue Hinweise anfordern zu können.",
        "htp-title": "Anleitung",
        "htp-intro": "*Settlement* ist ein Rätselspiel, bei dem es darum geht, ein Dorf in einer Welt zu errichten, die aus *Gras-*, *Wasser-* und *Baumfeldern* besteht.",
        "htp-village": "Dabei werden *Häuser* und *Wege* auf Grasfelder gesetzt und *Brücken* auf Wasserfelder. Bäume dienen nur als Hindernisse.",
        "htp-goal": "Das *Ziel* ist es, exakt so viele Häuser, Wege und Brücken zu platzieren, wie für jedes Rätsel am oberen Bildschirmrand angegeben ist.",
        "htp-rules": "Allerdings sind dabei ein paar *Regeln* einzuhalten:",
        "htp-rule-connected": "Alle Felder mit *Wegen* und *Brücken* müssen *verbunden* sein. Die Dorfbewohner wollen zu jedem Ort im Dorf gelangen können.",
        "htp-rule-isolation": "Jedes *Haus* muss sich *neben* einem Weg oder einer Brücke befinden. Die Dorfbewohner wollen ihre Häuser erreichen können.",
        "htp-rule-bridge": "*Brückenfelder* dürfen *nicht nebeneinander* platziert werden. Die Dorfbewohner können keine langen, stabilen Brücken bauen."
    }
};